/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.wedeploy.auth.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the WedeployAuthApp service. Represents a row in the &quot;WedeployAuthApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.security.wedeploy.auth.model.impl.WedeployAuthAppModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.security.wedeploy.auth.model.impl.WedeployAuthAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WedeployAuthApp
 * @see com.liferay.portal.security.wedeploy.auth.model.impl.WedeployAuthAppImpl
 * @see com.liferay.portal.security.wedeploy.auth.model.impl.WedeployAuthAppModelImpl
 * @generated
 */
@ProviderType
public interface WedeployAuthAppModel extends BaseModel<WedeployAuthApp>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wedeploy auth app model instance should use the {@link WedeployAuthApp} interface instead.
	 */

	/**
	 * Returns the primary key of this wedeploy auth app.
	 *
	 * @return the primary key of this wedeploy auth app
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wedeploy auth app.
	 *
	 * @param primaryKey the primary key of this wedeploy auth app
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this wedeploy auth app.
	 *
	 * @return the uuid of this wedeploy auth app
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this wedeploy auth app.
	 *
	 * @param uuid the uuid of this wedeploy auth app
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the wedeploy auth ID of this wedeploy auth app.
	 *
	 * @return the wedeploy auth ID of this wedeploy auth app
	 */
	public long getWedeployAuthId();

	/**
	 * Sets the wedeploy auth ID of this wedeploy auth app.
	 *
	 * @param wedeployAuthId the wedeploy auth ID of this wedeploy auth app
	 */
	public void setWedeployAuthId(long wedeployAuthId);

	/**
	 * Returns the client ID of this wedeploy auth app.
	 *
	 * @return the client ID of this wedeploy auth app
	 */
	@AutoEscape
	public String getClientId();

	/**
	 * Sets the client ID of this wedeploy auth app.
	 *
	 * @param clientId the client ID of this wedeploy auth app
	 */
	public void setClientId(String clientId);

	/**
	 * Returns the client name of this wedeploy auth app.
	 *
	 * @return the client name of this wedeploy auth app
	 */
	@AutoEscape
	public String getClientName();

	/**
	 * Sets the client name of this wedeploy auth app.
	 *
	 * @param clientName the client name of this wedeploy auth app
	 */
	public void setClientName(String clientName);

	/**
	 * Returns the secret of this wedeploy auth app.
	 *
	 * @return the secret of this wedeploy auth app
	 */
	@AutoEscape
	public String getSecret();

	/**
	 * Sets the secret of this wedeploy auth app.
	 *
	 * @param secret the secret of this wedeploy auth app
	 */
	public void setSecret(String secret);

	/**
	 * Returns the company ID of this wedeploy auth app.
	 *
	 * @return the company ID of this wedeploy auth app
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this wedeploy auth app.
	 *
	 * @param companyId the company ID of this wedeploy auth app
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WedeployAuthApp wedeployAuthApp);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WedeployAuthApp> toCacheModel();

	@Override
	public WedeployAuthApp toEscapedModel();

	@Override
	public WedeployAuthApp toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}